/**
 * Shotstack
 * Shotstack is a video, image and audio editing service that allows for the automated generation of videos, images and audio using JSON and a RESTful API.  You arrange and configure an edit and POST it to the API which will render your media and provide a file location when complete.  For more details visit [shotstack.io](https://shotstack.io) or checkout our [getting started](https://shotstack.io/docs/guide/) documentation.  There are three API\'s, one for editing and generating assets (Edit API), one for managing hosted assets (Serve API) and one for ingesting and transforming source assets (Ingest API).  Each API has it\'s own base URL and collection of endpoints. Each API uses the same set of API keys.  **[Edit API](#shotstack-edit)** - [https://api.shotstack.io/edit/{version}](#)<br> Edit videos, images and audio assets in the cloud using a simple JSON schema and templates.  **[Serve API](#shotstack-serve)** - [https://api.shotstack.io/serve/{version}](#)<br> Inspect and manage the hosting of assets generated by the Edit and Ingest APIs.  **[Ingest API](#shotstack-ingest)** - [https://api.shotstack.io/ingest/{version}](#)<br> Ingest (upload, store and transform) source footage, images, audio and fonts to be used by the Edit API.  **[Create API](#shotstack-create)** - [https://api.shotstack.io/create/{version}](#)<br> Generate images, videos, voice overs and text using built in and third party generative AI providers. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Asset } from './asset';
import { Offset } from './offset';
import { Transformation } from './transformation';
import { Transition } from './transition';

/**
* A clip is a container for a specific type of asset, i.e. a title, image, video, audio or html. You use a Clip to define when an asset will display on the timeline, how long it will play for and transitions, filters and effects to apply to it.
*/
export class Clip {
    'asset': Asset;
    /**
    * The start position of the Clip on the timeline, in seconds.
    */
    'start': number;
    /**
    * The length, in seconds, the Clip should play for.
    */
    'length': number;
    /**
    * Set how the asset should be scaled to fit the viewport using one of the following options:    <ul>     <li>`crop` <b>(default)</b> - scale the asset to fill the viewport while maintaining the aspect ratio. The asset will be cropped if it exceeds the bounds of the viewport.</li>     <li>`cover` - stretch the asset to fill the viewport without maintaining the aspect ratio.</li>     <li>`contain` - fit the entire asset within the viewport while maintaining the original aspect ratio.</li>     <li>`none` - preserves the original asset dimensions and does not apply any scaling.</li>   </ul>
    */
    'fit'?: Clip.FitEnum;
    /**
    * Scale the asset to a fraction of the viewport size - i.e. setting the scale to 0.5 will scale asset to half the size of the viewport. This is useful for picture-in-picture video and  scaling images such as logos and watermarks.
    */
    'scale'?: number;
    /**
    * Place the asset in one of nine predefined positions of the viewport. This is most effective for when the asset is scaled and you want to position the element to a specific position. <ul>   <li>`top` - top (center)</li>   <li>`topRight` - top right</li>   <li>`right` - right (center)</li>   <li>`bottomRight` - bottom right</li>   <li>`bottom` - bottom (center)</li>   <li>`bottomLeft` - bottom left</li>   <li>`left` - left (center)</li>   <li>`topLeft` - top left</li>   <li>`center` - center</li> </ul>
    */
    'position'?: Clip.PositionEnum;
    'offset'?: Offset;
    'transition'?: Transition;
    /**
    * A motion effect to apply to the Clip. <ul>   <li>`zoomIn` - slow zoom in</li>   <li>`zoomOut` - slow zoom out</li>   <li>`slideLeft` - slow slide (pan) left</li>   <li>`slideRight` - slow slide (pan) right</li>   <li>`slideUp` - slow slide (pan) up</li>   <li>`slideDown` - slow slide (pan) down</li> </ul> The motion effect speed can also be controlled by appending `Fast` or `Slow` to the effect, e.g. `zoomInFast` or `slideRightSlow`.
    */
    'effect'?: Clip.EffectEnum;
    /**
    * A filter effect to apply to the Clip. <ul>   <li>`boost` - boost contrast and saturation</li>   <li>`contrast` - increase contrast</li>   <li>`darken` - darken the scene</li>   <li>`greyscale` - remove colour</li>   <li>`lighten` - lighten the scene</li>   <li>`muted` - reduce saturation and contrast</li>   <li>`negative` - negative colors</li> </ul>
    */
    'filter'?: Clip.FilterEnum;
    /**
    * Sets the opacity of the Clip where 1 is opaque and 0 is transparent.
    */
    'opacity'?: number;
    'transform'?: Transformation;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "asset",
            "baseName": "asset",
            "type": "Asset"
        },
        {
            "name": "start",
            "baseName": "start",
            "type": "number"
        },
        {
            "name": "length",
            "baseName": "length",
            "type": "number"
        },
        {
            "name": "fit",
            "baseName": "fit",
            "type": "Clip.FitEnum"
        },
        {
            "name": "scale",
            "baseName": "scale",
            "type": "number"
        },
        {
            "name": "position",
            "baseName": "position",
            "type": "Clip.PositionEnum"
        },
        {
            "name": "offset",
            "baseName": "offset",
            "type": "Offset"
        },
        {
            "name": "transition",
            "baseName": "transition",
            "type": "Transition"
        },
        {
            "name": "effect",
            "baseName": "effect",
            "type": "Clip.EffectEnum"
        },
        {
            "name": "filter",
            "baseName": "filter",
            "type": "Clip.FilterEnum"
        },
        {
            "name": "opacity",
            "baseName": "opacity",
            "type": "number"
        },
        {
            "name": "transform",
            "baseName": "transform",
            "type": "Transformation"
        }    ];

    static getAttributeTypeMap() {
        return Clip.attributeTypeMap;
    }
}

export namespace Clip {
    export enum FitEnum {
        Cover = <any> 'cover',
        Contain = <any> 'contain',
        Crop = <any> 'crop',
        None = <any> 'none'
    }
    export enum PositionEnum {
        Top = <any> 'top',
        TopRight = <any> 'topRight',
        Right = <any> 'right',
        BottomRight = <any> 'bottomRight',
        Bottom = <any> 'bottom',
        BottomLeft = <any> 'bottomLeft',
        Left = <any> 'left',
        TopLeft = <any> 'topLeft',
        Center = <any> 'center'
    }
    export enum EffectEnum {
        ZoomIn = <any> 'zoomIn',
        ZoomInSlow = <any> 'zoomInSlow',
        ZoomInFast = <any> 'zoomInFast',
        ZoomOut = <any> 'zoomOut',
        ZoomOutSlow = <any> 'zoomOutSlow',
        ZoomOutFast = <any> 'zoomOutFast',
        SlideLeft = <any> 'slideLeft',
        SlideLeftSlow = <any> 'slideLeftSlow',
        SlideLeftFast = <any> 'slideLeftFast',
        SlideRight = <any> 'slideRight',
        SlideRightSlow = <any> 'slideRightSlow',
        SlideRightFast = <any> 'slideRightFast',
        SlideUp = <any> 'slideUp',
        SlideUpSlow = <any> 'slideUpSlow',
        SlideUpFast = <any> 'slideUpFast',
        SlideDown = <any> 'slideDown',
        SlideDownSlow = <any> 'slideDownSlow',
        SlideDownFast = <any> 'slideDownFast'
    }
    export enum FilterEnum {
        Boost = <any> 'boost',
        Contrast = <any> 'contrast',
        Darken = <any> 'darken',
        Greyscale = <any> 'greyscale',
        Lighten = <any> 'lighten',
        Muted = <any> 'muted',
        Negative = <any> 'negative'
    }
}
