/**
 * Shotstack
 * Official Typescript SDK for the Shotstack Cloud Video Editing API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Crop the sides of an asset by a relative amount. The size of the crop is specified using a scale between 0 and 1, relative to the screen width - i.e a left crop of 0.5 will crop half of the asset from the left, a top crop  of 0.25 will crop the top by quarter of the asset.
*/
export class Crop {
    /**
    * Crop from the top of the asset
    */
    'top'?: number;
    /**
    * Crop from the bottom of the asset
    */
    'bottom'?: number;
    /**
    * Crop from the left of the asset
    */
    'left'?: number;
    /**
    * Crop from the left of the asset
    */
    'right'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "top",
            "baseName": "top",
            "type": "number"
        },
        {
            "name": "bottom",
            "baseName": "bottom",
            "type": "number"
        },
        {
            "name": "left",
            "baseName": "left",
            "type": "number"
        },
        {
            "name": "right",
            "baseName": "right",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Crop.attributeTypeMap;
    }
}

