/**
 * Shotstack
 * Shotstack is a video, image and audio editing service that allows for the automated generation of videos, images and audio using JSON and a RESTful API.  You arrange and configure an edit and POST it to the API which will render your media and provide a file location when complete.  For more details visit [shotstack.io](https://shotstack.io) or checkout our [getting started](https://shotstack.io/docs/guide/) documentation.  There are three API\'s, one for editing and generating assets (Edit API), one for managing hosted assets (Serve API) and one for ingesting and transforming source assets (Ingest API).  Each API has it\'s own base URL and collection of endpoints. Each API uses the same set of API keys.  **[Edit API](#shotstack-edit)** - [https://api.shotstack.io/edit/{version}](#)<br> Edit videos, images and audio assets in the cloud using a simple JSON schema and templates.  **[Serve API](#shotstack-serve)** - [https://api.shotstack.io/serve/{version}](#)<br> Inspect and manage the hosting of assets generated by the Edit and Ingest APIs.  **[Ingest API](#shotstack-ingest)** - [https://api.shotstack.io/ingest/{version}](#)<br> Ingest (upload, store and transform) source footage, images, audio and fonts to be used by the Edit API.  **[Create API](#shotstack-create)** - [https://api.shotstack.io/create/{version}](#)<br> Generate images, videos, voice overs and text using built in and third party generative AI providers. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MuxDestination } from './muxDestination';
import { S3Destination } from './s3Destination';
import { S3DestinationOptions } from './s3DestinationOptions';
import { ShotstackDestination } from './shotstackDestination';

/**
* A destination is a location where assets can be sent to for serving or hosting. Videos, images and audio files that are rendered by the Edit API and source and rendition files generated by the Ingest API can be sent to  destinations. A file can be sent to one or more destinations including 3rd party destinations.  By default all ingested and generated assets are automatically sent to the  [Shotstack hosting destination](https://shotstack.io/docs/guide/serving-assets/hosting). You can  [opt-out](https://shotstack.io/docs/guide/serving-assets/self-host) from by setting the Shotstack destination  **exclude** property to **true**.   The following destinations are available: <ul>   <li><a href=\"#tocs_shotstackdestination\">ShotstackDestination</a></li>   <li><a href=\"#tocs_muxdestination\">MuxDestination</a></li>   <li><a href=\"#tocs_s3destination\">S3Destination</a></li> </ul>
*/
export class Destinations {
    /**
    * The destination to send rendered assets to - set to `s3` for S3.
    */
    'provider': string = 's3';
    /**
    * Set to `true` to [opt-out](https://shotstack.io/docs/guide/serving-assets/self-host) from the Shotstack hosting and CDN service. All files must be downloaded within 24 hours of rendering.
    */
    'exclude'?: boolean;
    'options'?: S3DestinationOptions;

    static discriminator: string | undefined = "destinations";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "provider",
            "baseName": "provider",
            "type": "string"
        },
        {
            "name": "exclude",
            "baseName": "exclude",
            "type": "boolean"
        },
        {
            "name": "options",
            "baseName": "options",
            "type": "S3DestinationOptions"
        }    ];

    static getAttributeTypeMap() {
        return Destinations.attributeTypeMap;
    }
}

