/**
 * Shotstack
 * Official PHP SDK for the Shotstack Cloud Video Editing API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DIDTextToAvatarOptions } from './dIDTextToAvatarOptions';

/**
* Generate assets using the third party D-ID provider AI services.  The following AI generation services are available: <ul>   <li><a href=\"#tocs_didtexttoavataroptions\">DidTextToAvatarOptions</a></li> </ul>
*/
export class DIDGeneratedAssetOptions {
    /**
    * The type of asset to generate - set to `text-to-avatar` for text-to-avatar.
    */
    'type': DIDGeneratedAssetOptions.TypeEnum;
    /**
    * The text or script that the avatar will narrate.
    */
    'text': string;
    /**
    * The avatar character to generate. Select from the list of available avatars: <ul>   <li>`jack`</li>   <li>`lana`</li>   <li>`lily`</li>   <li>`matt`</li>   <li>`rian`</li> </ul>
    */
    'avatar': DIDGeneratedAssetOptions.AvatarEnum;
    /**
    * The background color of the video.
    */
    'background'?: string;

    static discriminator: string | undefined = "type";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "DIDGeneratedAssetOptions.TypeEnum"
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "string"
        },
        {
            "name": "avatar",
            "baseName": "avatar",
            "type": "DIDGeneratedAssetOptions.AvatarEnum"
        },
        {
            "name": "background",
            "baseName": "background",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return DIDGeneratedAssetOptions.attributeTypeMap;
    }
}

export namespace DIDGeneratedAssetOptions {
    export enum TypeEnum {
        TEXT_TO_AVATAR = <any> 'text-to-avatar'
    }
    export enum AvatarEnum {
        JACK = <any> 'jack',
        LANA = <any> 'lana',
        LILY = <any> 'lily',
        MATT = <any> 'matt',
        RIAN = <any> 'rian'
    }
}
