/**
 * Shotstack
 * Shotstack is a video, image and audio editing service that allows for the automated generation of videos, images and audio using JSON and a RESTful API.  You arrange and configure an edit and POST it to the API which will render your media and provide a file location when complete.  For more details visit [shotstack.io](https://shotstack.io) or checkout our [getting started](https://shotstack.io/docs/guide/) documentation.  There are three API\'s, one for editing and generating assets (Edit API), one for managing hosted assets (Serve API) and one for ingesting and transforming source assets (Ingest API).  Each API has it\'s own base URL and collection of endpoints. Each API uses the same set of API keys.  **[Edit API](#shotstack-edit)** - [https://api.shotstack.io/edit/{version}](#)<br> Edit videos, images and audio assets in the cloud using a simple JSON schema and templates.  **[Serve API](#shotstack-serve)** - [https://api.shotstack.io/serve/{version}](#)<br> Inspect and manage the hosting of assets generated by the Edit and Ingest APIs.  **[Ingest API](#shotstack-ingest)** - [https://api.shotstack.io/ingest/{version}](#)<br> Ingest (upload, store and transform) source footage, images, audio and fonts to be used by the Edit API.  **[Create API](#shotstack-create)** - [https://api.shotstack.io/create/{version}](#)<br> Generate images, videos, voice overs and text using built in and third party generative AI providers. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Options for the D-ID text-to-avatar service. Set the text to be converted to an avatar and configure the avatar and background. The output will be generated as an MP4 video file.
*/
export class DIDTextToAvatarOptions {
    /**
    * The type of asset to generate - set to `text-to-avatar` for text-to-avatar.
    */
    'type': DIDTextToAvatarOptions.TypeEnum;
    /**
    * The text or script that the avatar will narrate.
    */
    'text': string;
    /**
    * The avatar character to generate. Select from the list of available avatars: <ul>   <li>`jack`</li>   <li>`lana`</li>   <li>`lily`</li>   <li>`matt`</li>   <li>`rian`</li> </ul>
    */
    'avatar': DIDTextToAvatarOptions.AvatarEnum;
    /**
    * The background color of the video.
    */
    'background'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "DIDTextToAvatarOptions.TypeEnum"
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "string"
        },
        {
            "name": "avatar",
            "baseName": "avatar",
            "type": "DIDTextToAvatarOptions.AvatarEnum"
        },
        {
            "name": "background",
            "baseName": "background",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return DIDTextToAvatarOptions.attributeTypeMap;
    }
}

export namespace DIDTextToAvatarOptions {
    export enum TypeEnum {
        TextToAvatar = <any> 'text-to-avatar'
    }
    export enum AvatarEnum {
        Jack = <any> 'jack',
        Lana = <any> 'lana',
        Lily = <any> 'lily',
        Matt = <any> 'matt',
        Rian = <any> 'rian'
    }
}
