/**
 * Shotstack
 * Official PHP SDK for the Shotstack Cloud Video Editing API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Options for the D-ID text-to-avatar service. Set the text to be converted to an avatar and configure the avatar and background. The output will be generated as an MP4 video file.
*/
export class DIDTextToAvatarOptions {
    /**
    * The type of asset to generate - set to `text-to-avatar` for text-to-avatar.
    */
    'type': DIDTextToAvatarOptions.TypeEnum;
    /**
    * The text or script that the avatar will narrate.
    */
    'text': string;
    /**
    * The avatar character to generate. Select from the list of available avatars: <ul>   <li>`jack`</li>   <li>`lana`</li>   <li>`lily`</li>   <li>`matt`</li>   <li>`rian`</li> </ul>
    */
    'avatar': DIDTextToAvatarOptions.AvatarEnum;
    /**
    * The background color of the video.
    */
    'background'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "DIDTextToAvatarOptions.TypeEnum"
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "string"
        },
        {
            "name": "avatar",
            "baseName": "avatar",
            "type": "DIDTextToAvatarOptions.AvatarEnum"
        },
        {
            "name": "background",
            "baseName": "background",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return DIDTextToAvatarOptions.attributeTypeMap;
    }
}

export namespace DIDTextToAvatarOptions {
    export enum TypeEnum {
        TEXT_TO_AVATAR = <any> 'text-to-avatar'
    }
    export enum AvatarEnum {
        JACK = <any> 'jack',
        LANA = <any> 'lana',
        LILY = <any> 'lily',
        MATT = <any> 'matt',
        RIAN = <any> 'rian'
    }
}
