/**
 * Shotstack
 * Official PHP SDK for the Shotstack Cloud Video Editing API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Options for the Dolby.io audio enhancement provider.
*/
export class DolbyEnhancementOptions {
    /**
    * The preset to use for the audio enhancement. The following presets are available: <ul>   <li>`conference` - Conference</li>   <li>`interview` - Interview</li>   <li>`lecture` - Lecture</li>   <li>`meeting` - Meeting</li>   <li>`mobile_phone` - Mobile Phone</li>   <li>`music` - Music</li>   <li>`podcast` - Podcast</li>   <li>`studio` - Studio</li>   <li>`voice_over` - Voice Over</li> </ul>
    */
    'preset': DolbyEnhancementOptions.PresetEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "preset",
            "baseName": "preset",
            "type": "DolbyEnhancementOptions.PresetEnum"
        }    ];

    static getAttributeTypeMap() {
        return DolbyEnhancementOptions.attributeTypeMap;
    }
}

export namespace DolbyEnhancementOptions {
    export enum PresetEnum {
        CONFERENCE = <any> 'conference',
        INTERVIEW = <any> 'interview',
        LECTURE = <any> 'lecture',
        MEETING = <any> 'meeting',
        MOBILE_PHONE = <any> 'mobile_phone',
        MUSIC = <any> 'music',
        PODCAST = <any> 'podcast',
        STUDIO = <any> 'studio',
        VOICE_OVER = <any> 'voice_over'
    }
}
