/**
 * Shotstack
 * Official Typescript SDK for the Shotstack Cloud Video Editing API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ElevenLabsTextToSpeechOptions } from './elevenLabsTextToSpeechOptions';

/**
* Generate assets using the third party ElevenLabs provider AI services.  The following AI generation services are available: <ul>   <li><a href=\"#tocs_elevenlabstexttospeechoptions\">ElevenLabsTextToSpeechOptions</a></li> </ul>
*/
export class ElevenLabsGeneratedAssetOptions {
    /**
    * The type of asset to generate - set to `text-to-speech` for text-to-speech.
    */
    'type': ElevenLabsGeneratedAssetOptions.TypeEnum;
    /**
    * The text to convert to speech.
    */
    'text': string;
    /**
    * The voice to use for the text-to-speech conversion. Select a voice from the list of available voices: <ul>   <li>`Adam`</li>   <li>`Antoni`</li>   <li>`Arnold`</li>   <li>`Bella`</li>   <li>`Domi`</li>   <li>`Elli`</li>   <li>`Josh`</li>   <li>`Rachel`</li>   <li>`Sam`</li> </ul>
    */
    'voice': ElevenLabsGeneratedAssetOptions.VoiceEnum;

    static discriminator: string | undefined = "type";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "ElevenLabsGeneratedAssetOptions.TypeEnum"
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "string"
        },
        {
            "name": "voice",
            "baseName": "voice",
            "type": "ElevenLabsGeneratedAssetOptions.VoiceEnum"
        }    ];

    static getAttributeTypeMap() {
        return ElevenLabsGeneratedAssetOptions.attributeTypeMap;
    }
}

export namespace ElevenLabsGeneratedAssetOptions {
    export enum TypeEnum {
        TEXT_TO_SPEECH = <any> 'text-to-speech'
    }
    export enum VoiceEnum {
        ADAM = <any> 'Adam',
        ANTONI = <any> 'Antoni',
        ARNOLD = <any> 'Arnold',
        BELLA = <any> 'Bella',
        DOMI = <any> 'Domi',
        ELLI = <any> 'Elli',
        JOSH = <any> 'Josh',
        RACHEL = <any> 'Rachel',
        SAM = <any> 'Sam'
    }
}
