/**
 * Shotstack
 * Shotstack is a video, image and audio editing service that allows for the automated generation of videos, images and audio using JSON and a RESTful API.  You arrange and configure an edit and POST it to the API which will render your media and provide a file location when complete.  For more details visit [shotstack.io](https://shotstack.io) or checkout our [getting started](https://shotstack.io/docs/guide/) documentation.  There are three API\'s, one for editing and generating assets (Edit API), one for managing hosted assets (Serve API) and one for ingesting and transforming source assets (Ingest API).  Each API has it\'s own base URL and collection of endpoints. Each API uses the same set of API keys.  **[Edit API](#shotstack-edit)** - [https://api.shotstack.io/edit/{version}](#)<br> Edit videos, images and audio assets in the cloud using a simple JSON schema and templates.  **[Serve API](#shotstack-serve)** - [https://api.shotstack.io/serve/{version}](#)<br> Inspect and manage the hosting of assets generated by the Edit and Ingest APIs.  **[Ingest API](#shotstack-ingest)** - [https://api.shotstack.io/ingest/{version}](#)<br> Ingest (upload, store and transform) source footage, images, audio and fonts to be used by the Edit API.  **[Create API](#shotstack-create)** - [https://api.shotstack.io/create/{version}](#)<br> Generate images, videos, voice overs and text using built in and third party generative AI providers. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Options for the ElevenLabs text-to-speech service. Set the text to be converted to speech and choose a voice to set the speaking style. The output will be generated as an MP3 audio file.
*/
export class ElevenLabsTextToSpeechOptions {
    /**
    * The type of asset to generate - set to `text-to-speech` for text-to-speech.
    */
    'type': ElevenLabsTextToSpeechOptions.TypeEnum;
    /**
    * The text to convert to speech.
    */
    'text': string;
    /**
    * The voice to use for the text-to-speech conversion. Select a voice from the list of available voices: <ul>   <li>`Adam`</li>   <li>`Antoni`</li>   <li>`Arnold`</li>   <li>`Bella`</li>   <li>`Domi`</li>   <li>`Elli`</li>   <li>`Josh`</li>   <li>`Rachel`</li>   <li>`Sam`</li> </ul>
    */
    'voice': ElevenLabsTextToSpeechOptions.VoiceEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "ElevenLabsTextToSpeechOptions.TypeEnum"
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "string"
        },
        {
            "name": "voice",
            "baseName": "voice",
            "type": "ElevenLabsTextToSpeechOptions.VoiceEnum"
        }    ];

    static getAttributeTypeMap() {
        return ElevenLabsTextToSpeechOptions.attributeTypeMap;
    }
}

export namespace ElevenLabsTextToSpeechOptions {
    export enum TypeEnum {
        TEXT_TO_SPEECH = <any> 'text-to-speech'
    }
    export enum VoiceEnum {
        ADAM = <any> 'Adam',
        ANTONI = <any> 'Antoni',
        ARNOLD = <any> 'Arnold',
        BELLA = <any> 'Bella',
        DOMI = <any> 'Domi',
        ELLI = <any> 'Elli',
        JOSH = <any> 'Josh',
        RACHEL = <any> 'Rachel',
        SAM = <any> 'Sam'
    }
}
