/**
 * Shotstack
 * Official PHP SDK for the Shotstack Cloud Video Editing API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ElevenLabsGeneratedAssetOptions } from './elevenLabsGeneratedAssetOptions';

/**
* Generate assets using ElevenLabs. ElevenLabs provide a text-to-speech service. The ElevenLabs provider works on a bring-your-own-key basis, credentials are required and must be added via the  [dashboard](https://dashboard.shotstack.io/integrations/elevenlabs), not in the request.
*/
export class ElevenLabsGeneratedAsset {
    /**
    * The name of the provider - set to `elevenlabs` for ElevenLabs.
    */
    'provider': ElevenLabsGeneratedAsset.ProviderEnum = ElevenLabsGeneratedAsset.ProviderEnum.ELEVENLABS;
    'options': ElevenLabsGeneratedAssetOptions;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "provider",
            "baseName": "provider",
            "type": "ElevenLabsGeneratedAsset.ProviderEnum"
        },
        {
            "name": "options",
            "baseName": "options",
            "type": "ElevenLabsGeneratedAssetOptions"
        }    ];

    static getAttributeTypeMap() {
        return ElevenLabsGeneratedAsset.attributeTypeMap;
    }
}

export namespace ElevenLabsGeneratedAsset {
    export enum ProviderEnum {
        ELEVENLABS = <any> 'elevenlabs'
    }
}
