/**
 * Shotstack
 * Official PHP SDK for the Shotstack Cloud Video Editing API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AudioEnhancement } from './audioEnhancement';

/**
* Enhancements that can be applied to a rendition. Currently only supports the Dolby audio enhancement.
*/
export class Enhancements {
    'audio'?: AudioEnhancement;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "audio",
            "baseName": "audio",
            "type": "AudioEnhancement"
        }    ];

    static getAttributeTypeMap() {
        return Enhancements.attributeTypeMap;
    }
}

