/**
 * Shotstack
 * Official PHP SDK for the Shotstack Cloud Video Editing API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The id and attributes of the generated asset.
*/
export class GeneratedAssetResponseAttributes {
    /**
    * The owner id of the asset.
    */
    'owner': string;
    /**
    * The native or third party provider that generated the asset, `shotstack`, `elevenlabs`, `heygen` or `d-id`.
    */
    'provider': GeneratedAssetResponseAttributes.ProviderEnum;
    /**
    * The type of service used to generate the asset, `text-to-speech` or `text-to-avatar`.
    */
    'type': GeneratedAssetResponseAttributes.TypeEnum;
    /**
    * The URL of the asset file hosted by Shotstack. The file at the URL can be used by the Edit API. Generated asset file URL\'s consist of a base URL (AWS bucket), owner id, asset id and extension. The extension varies depending on the type of file generated.
    */
    'url'?: string;
    /**
    * The status of the asset file generation task. <ul>   <li>`queued` - generation task is queued waiting to be processed</li>   <li>`processing` - the asset is being generated by the provider</li>   <li>`saving` - the asset is being saved to Shotstack</li>   <li>`done` - the asset has been generated and stored</li>   <li>`failed` - there was an error generating the asset</li> </ul>
    */
    'status': GeneratedAssetResponseAttributes.StatusEnum;
    /**
    * The time the generate asset task was initially queued.
    */
    'created': string;
    /**
    * The time the asset status was last updated.
    */
    'updated': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "owner",
            "baseName": "owner",
            "type": "string"
        },
        {
            "name": "provider",
            "baseName": "provider",
            "type": "GeneratedAssetResponseAttributes.ProviderEnum"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "GeneratedAssetResponseAttributes.TypeEnum"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "GeneratedAssetResponseAttributes.StatusEnum"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "string"
        },
        {
            "name": "updated",
            "baseName": "updated",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return GeneratedAssetResponseAttributes.attributeTypeMap;
    }
}

export namespace GeneratedAssetResponseAttributes {
    export enum ProviderEnum {
        SHOTSTACK = <any> 'shotstack',
        ELEVENLABS = <any> 'elevenlabs',
        HEYGEN = <any> 'heygen',
        D_ID = <any> 'd-id'
    }
    export enum TypeEnum {
        SPEECH = <any> 'text-to-speech',
        AVATAR = <any> 'text-to-avatar'
    }
    export enum StatusEnum {
        QUEUED = <any> 'queued',
        PROCESSING = <any> 'processing',
        SAVING = <any> 'saving',
        DONE = <any> 'done',
        FAILED = <any> 'failed'
    }
}
