/**
 * Shotstack
 * Shotstack is a video, image and audio editing service that allows for the automated generation of videos, images and audio using JSON and a RESTful API.  You arrange and configure an edit and POST it to the API which will render your media and provide a file location when complete.  For more details visit [shotstack.io](https://shotstack.io) or checkout our [getting started](https://shotstack.io/docs/guide/) documentation.  There are three API\'s, one for editing and generating assets (Edit API), one for managing hosted assets (Serve API) and one for ingesting and transforming source assets (Ingest API).  Each API has it\'s own base URL and collection of endpoints. Each API uses the same set of API keys.  **[Edit API](#shotstack-edit)** - [https://api.shotstack.io/edit/{version}](#)<br> Edit videos, images and audio assets in the cloud using a simple JSON schema and templates.  **[Serve API](#shotstack-serve)** - [https://api.shotstack.io/serve/{version}](#)<br> Inspect and manage the hosting of assets generated by the Edit and Ingest APIs.  **[Ingest API](#shotstack-ingest)** - [https://api.shotstack.io/ingest/{version}](#)<br> Ingest (upload, store and transform) source footage, images, audio and fonts to be used by the Edit API.  **[Create API](#shotstack-create)** - [https://api.shotstack.io/create/{version}](#)<br> Generate images, videos, voice overs and text using built in and third party generative AI providers. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DIDGeneratedAsset } from './dIDGeneratedAsset';
import { DIDTextToAvatarOptions } from './dIDTextToAvatarOptions';
import { ElevenLabsGeneratedAsset } from './elevenLabsGeneratedAsset';
import { HeyGenGeneratedAsset } from './heyGenGeneratedAsset';
import { ShotstackGeneratedAsset } from './shotstackGeneratedAsset';

/**
* A generated asset is a media asset created by the Create API. You can use native or third party providers to generate video, audio and image files using Generative AI services like text-to-speech and text-to-avatar. The following providers are currently available: <ul>   <li><a href=\"#tocs_shotstackgeneratedasset\">ShotstackGeneratedAsset</a></li>   <li><a href=\"#tocs_elevenlabsgeneratedasset\">ElevenLabsGeneratedAsset</a></li>   <li><a href=\"#tocs_heygengeneratedasset\">HeyGenGeneratedAsset</a></li>   <li><a href=\"#tocs_didgeneratedasset\">DIDGeneratedAsset</a></li> </ul>
*/
export class GeneratedAsset {
    /**
    * The name of the provider - set to `d-id` for D-ID.
    */
    'provider'?: GeneratedAsset.ProviderEnum = GeneratedAsset.ProviderEnum.D_ID;
    'options'?: DIDTextToAvatarOptions;

    static discriminator: string | undefined = "provider";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "provider",
            "baseName": "provider",
            "type": "GeneratedAsset.ProviderEnum"
        },
        {
            "name": "options",
            "baseName": "options",
            "type": "DIDTextToAvatarOptions"
        }    ];

    static getAttributeTypeMap() {
        return GeneratedAsset.attributeTypeMap;
    }
}

export namespace GeneratedAsset {
    export enum ProviderEnum {
        D_ID = <any> 'd-id'
    }
}
