/**
 * Shotstack
 * Official PHP SDK for the Shotstack Cloud Video Editing API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Pass additional options to control how files are stored in Google Cloud Storage.
*/
export class GoogleCloudStorageDestinationOptions {
    /**
    * The bucket name to send files to. The bucket must exist in the Google Cloud Storage account before files can be sent.
    */
    'bucket': string;
    /**
    * A prefix for the file being sent. This is typically a folder name, i.e. `videos` or `customerId/videos`.
    */
    'prefix'?: string;
    /**
    * Use your own filename instead of the default filenames generated by Shotstack. Note: omit the file extension as this will be appended depending on the output format. Also `-poster.jpg` and `-thumb.jpg` will be appended for poster and thumbnail images.
    */
    'filename'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "bucket",
            "baseName": "bucket",
            "type": "string"
        },
        {
            "name": "prefix",
            "baseName": "prefix",
            "type": "string"
        },
        {
            "name": "filename",
            "baseName": "filename",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return GoogleCloudStorageDestinationOptions.attributeTypeMap;
    }
}

