/**
 * Shotstack
 * Official PHP SDK for the Shotstack Cloud Video Editing API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { GoogleCloudStorageDestinationOptions } from './googleCloudStorageDestinationOptions';

/**
* Send videos and assets to a [Google Cloud Storage](https://cloud.google.com/storage) bucket. Send files with your own prefix and filename. Google Cloud credentials are required and added via the [dashboard](https://dashboard.shotstack.io/integrations/google-cloud-storage), not in the request.
*/
export class GoogleCloudStorageDestination {
    /**
    * The destination to send assets to - set to `google-cloud-storage` for Google Cloud Storage.
    */
    'provider': string = 'google-cloud-storage';
    'options'?: GoogleCloudStorageDestinationOptions;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "provider",
            "baseName": "provider",
            "type": "string"
        },
        {
            "name": "options",
            "baseName": "options",
            "type": "GoogleCloudStorageDestinationOptions"
        }    ];

    static getAttributeTypeMap() {
        return GoogleCloudStorageDestination.attributeTypeMap;
    }
}

