/**
 * Shotstack
 * Official PHP SDK for the Shotstack Cloud Video Editing API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* A merge field consists of a key; `find`, and a value; `replace`. Merge fields can be used to replace placeholders within the JSON edit to create re-usable templates. Placeholders should be a string with double brace delimiters, i.e. `\"{{NAME}}\"`. A placeholder can be used for any value within the JSON edit.
*/
export class MergeField {
    /**
    * The string to find <u>without</u> delimiters.
    */
    'find': string;
    /**
    * The replacement value. The replacement can be any valid JSON type - string, boolean, number, etc...
    */
    'replace': any | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "find",
            "baseName": "find",
            "type": "string"
        },
        {
            "name": "replace",
            "baseName": "replace",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return MergeField.attributeTypeMap;
    }
}

