/**
 * Shotstack
 * Official PHP SDK for the Shotstack Cloud Video Editing API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Pass additional options to control how Mux processes video. Currently supports playback_policy and passthrough options.
*/
export class MuxDestinationOptions {
    /**
    * Sets the Mux `playback_policy` option. Value is an array of strings - use `public`, `signed`, or both.
    */
    'playbackPolicy'?: Array<MuxDestinationOptions.PlaybackPolicyEnum>;
    /**
    * Sets the Mux `passthrough` option. Max 255 characters.
    */
    'passthrough'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "playbackPolicy",
            "baseName": "playbackPolicy",
            "type": "Array<MuxDestinationOptions.PlaybackPolicyEnum>"
        },
        {
            "name": "passthrough",
            "baseName": "passthrough",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return MuxDestinationOptions.attributeTypeMap;
    }
}

export namespace MuxDestinationOptions {
    export enum PlaybackPolicyEnum {
        PUBLIC = <any> 'public',
        SIGNED = <any> 'signed'
    }
}
