/**
 * Shotstack
 * Official PHP SDK for the Shotstack Cloud Video Editing API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Rendition } from './rendition';
import { Transcription } from './transcription';

/**
* The output renditions and transformations that should be generated from the source file.
*/
export class Outputs {
    /**
    * The output renditions and transformations that should be generated from the source file.
    */
    'renditions'?: Array<Rendition>;
    'transcription'?: Transcription;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "renditions",
            "baseName": "renditions",
            "type": "Array<Rendition>"
        },
        {
            "name": "transcription",
            "baseName": "transcription",
            "type": "Transcription"
        }    ];

    static getAttributeTypeMap() {
        return Outputs.attributeTypeMap;
    }
}

