/**
 * Shotstack
 * Official PHP SDK for the Shotstack Cloud Video Editing API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { RenditionResponseAttributes } from './renditionResponseAttributes';

/**
* The list of outputs generated from the source file. Currently supports renditions which are versions of the source file with different transformations applied.
*/
export class OutputsResponse {
    /**
    * The list of renditions generated from the source file.
    */
    'renditions'?: Array<RenditionResponseAttributes>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "renditions",
            "baseName": "renditions",
            "type": "Array<RenditionResponseAttributes>"
        }    ];

    static getAttributeTypeMap() {
        return OutputsResponse.attributeTypeMap;
    }
}

