/**
 * Shotstack
 * Official Typescript SDK for the Shotstack Cloud Video Editing API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Generate a poster image for the video at a specific point from the timeline. The poster image size will match the size of the output video.
*/
export class Poster {
    /**
    * The point on the timeline in seconds to capture a single frame to use as the poster image.
    */
    'capture': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "capture",
            "baseName": "capture",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Poster.attributeTypeMap;
    }
}

