/**
 * Shotstack
 * Official Typescript SDK for the Shotstack Cloud Video Editing API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { RenderResponseData } from './renderResponseData';

/**
* The response received after a [render status request](#get-render-status) is submitted. The response includes  details about status of a render and the output URL.
*/
export class RenderResponse {
    /**
    * `true` if status available, else `false`.
    */
    'success': boolean;
    /**
    * `OK` or an error message.
    */
    'message': string;
    'response': RenderResponseData;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "success",
            "baseName": "success",
            "type": "boolean"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "response",
            "baseName": "response",
            "type": "RenderResponseData"
        }    ];

    static getAttributeTypeMap() {
        return RenderResponse.attributeTypeMap;
    }
}

