/**
 * Shotstack
 * Official Typescript SDK for the Shotstack Cloud Video Editing API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Rotate a clip by the specified angle in degrees. Rotation origin is set based on the clips `position`.
*/
export class RotateTransformation {
    /**
    * The angle to rotate the clip. Can be 0 to 360, or 0 to -360. Using a positive number rotates the clip clockwise, negative numbers counter-clockwise.
    */
    'angle'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "angle",
            "baseName": "angle",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return RotateTransformation.attributeTypeMap;
    }
}

