/**
 * Shotstack
 * Official Typescript SDK for the Shotstack Cloud Video Editing API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { S3DestinationOptions } from './s3DestinationOptions';

/**
* Send videos and assets to an [Amazon S3](https://shotstack.io/docs/guide/serving-assets/destinations/s3/) bucket. Send files to any region with your own prefix and filename. AWS credentials are required and added via the [dashboard](https://dashboard.shotstack.io/integrations/s3), not in the request.
*/
export class S3Destination {
    /**
    * The destination to send assets to - set to `s3` for S3.
    */
    'provider': string = 's3';
    'options'?: S3DestinationOptions;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "provider",
            "baseName": "provider",
            "type": "string"
        },
        {
            "name": "options",
            "baseName": "options",
            "type": "S3DestinationOptions"
        }    ];

    static getAttributeTypeMap() {
        return S3Destination.attributeTypeMap;
    }
}

