/**
 * Shotstack
 * Official Typescript SDK for the Shotstack Cloud Video Editing API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Options for the Shotstack text-to-image service. Set a text prompt to generate an image from. The output will be  generated as a PNG file available at the URL returned in the response.
*/
export class ShotstackTextToImageOptions {
    /**
    * The type of asset to generate - set to `text-to-image` for text-to-image.
    */
    'type': ShotstackTextToImageOptions.TypeEnum = ShotstackTextToImageOptions.TypeEnum.TEXT_TO_IMAGE;
    /**
    * The text prompt to generate an image from.
    */
    'prompt': string;
    /**
    * The width of the image in pixels.
    */
    'width': number;
    /**
    * The height of the image in pixels.
    */
    'height': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "ShotstackTextToImageOptions.TypeEnum"
        },
        {
            "name": "prompt",
            "baseName": "prompt",
            "type": "string"
        },
        {
            "name": "width",
            "baseName": "width",
            "type": "number"
        },
        {
            "name": "height",
            "baseName": "height",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return ShotstackTextToImageOptions.attributeTypeMap;
    }
}

export namespace ShotstackTextToImageOptions {
    export enum TypeEnum {
        TEXT_TO_IMAGE = <any> 'text-to-image'
    }
}
