/**
 * Shotstack
 * Official PHP SDK for the Shotstack Cloud Video Editing API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ShotstackGeneratedAssetOptions } from './shotstackGeneratedAssetOptions';

/**
* Generate assets using the native Shotstack provider. Shotstack provides a text-to-speech and a text-to-image service. The Shotstack provider works natively with your existing API key, no additional credentials are required.
*/
export class ShotstackGeneratedAsset {
    /**
    * The name of the provider - set to `shotstack` for Shotstack.
    */
    'provider': ShotstackGeneratedAsset.ProviderEnum = ShotstackGeneratedAsset.ProviderEnum.SHOTSTACK;
    'options': ShotstackGeneratedAssetOptions;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "provider",
            "baseName": "provider",
            "type": "ShotstackGeneratedAsset.ProviderEnum"
        },
        {
            "name": "options",
            "baseName": "options",
            "type": "ShotstackGeneratedAssetOptions"
        }    ];

    static getAttributeTypeMap() {
        return ShotstackGeneratedAsset.attributeTypeMap;
    }
}

export namespace ShotstackGeneratedAsset {
    export enum ProviderEnum {
        SHOTSTACK = <any> 'shotstack'
    }
}
