/**
 * Shotstack
 * Official PHP SDK for the Shotstack Cloud Video Editing API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Options for the Shotstack image-to-video service. Set the URL of an image to convert in to a video. The output will be generated as an MP4 file available at the URL returned in the response.
*/
export class ShotstackImageToVideoOptions {
    /**
    * The type of asset to generate - set to `image-to-video` for image-to-video.
    */
    'type': ShotstackImageToVideoOptions.TypeEnum = ShotstackImageToVideoOptions.TypeEnum.IMAGE_TO_VIDEO;
    /**
    * The URL of the image to convert to video. The URL must be publicly accessible or include credentials. The image dimensions must exactly match one of the following: 1024px x 576px, 576px x 1024px or 768px x 768px.
    */
    'imageUrl': string;
    /**
    * The guidance scale determines how closely the generated video will match the image. Lower numbers allow for more creative freedom. A number between 0 and 10.
    */
    'guidanceScale'?: number = 1.8;
    /**
    * The amount of motion in the video. A number between 1 and 255.
    */
    'motion'?: number = 127;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "ShotstackImageToVideoOptions.TypeEnum"
        },
        {
            "name": "imageUrl",
            "baseName": "imageUrl",
            "type": "string"
        },
        {
            "name": "guidanceScale",
            "baseName": "guidanceScale",
            "type": "number"
        },
        {
            "name": "motion",
            "baseName": "motion",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return ShotstackImageToVideoOptions.attributeTypeMap;
    }
}

export namespace ShotstackImageToVideoOptions {
    export enum TypeEnum {
        IMAGE_TO_VIDEO = <any> 'image-to-video'
    }
}
