/**
 * Shotstack
 * Official PHP SDK for the Shotstack Cloud Video Editing API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* A music or audio file in mp3 format that plays for the duration of the rendered video or the length of the audio file, which ever is shortest.
*/
export class Soundtrack {
    /**
    * The URL of the mp3 audio file. The URL must be publicly accessible or include credentials.
    */
    'src': string;
    /**
    * The effect to apply to the audio file <ul>   <li>`fadeIn` - fade volume in only</li>   <li>`fadeOut` - fade volume out only</li>   <li>`fadeInFadeOut` - fade volume in and out</li> </ul>
    */
    'effect'?: Soundtrack.EffectEnum;
    /**
    * Set the volume for the soundtrack between 0 and 1 where 0 is muted and 1 is full volume (defaults to 1).
    */
    'volume'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "src",
            "baseName": "src",
            "type": "string"
        },
        {
            "name": "effect",
            "baseName": "effect",
            "type": "Soundtrack.EffectEnum"
        },
        {
            "name": "volume",
            "baseName": "volume",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Soundtrack.attributeTypeMap;
    }
}

export namespace Soundtrack {
    export enum EffectEnum {
        FADE_IN = <any> 'fadeIn',
        FADE_OUT = <any> 'fadeOut',
        FADE_IN_FADE_OUT = <any> 'fadeInFadeOut'
    }
}
