/**
 * Shotstack
 * Official Typescript SDK for the Shotstack Cloud Video Editing API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SourceResponseData } from './sourceResponseData';

/**
* A list of all ingested source files fetched or uploaded to a users account.
*/
export class SourceListResponse {
    /**
    * An array of ingested source files.
    */
    'data': Array<SourceResponseData>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<SourceResponseData>"
        }    ];

    static getAttributeTypeMap() {
        return SourceListResponse.attributeTypeMap;
    }
}

