/**
 * Shotstack
 * Official PHP SDK for the Shotstack Cloud Video Editing API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Destinations } from './destinations';
import { Outputs } from './outputs';

/**
* The details of the file to be ingested and any transformations to be applied. Once the source file has been ingested, new renditions can be created from it. The renditions are specified in the **outputs** property. A rendition is a new version, generated from the source. This can be used to create new sizes and aspect ratios tht serve different purposes within an application.
*/
export class Source {
    /**
    * The URL of the file to be ingested. The URL must be publicly accessible or include credentials.
    */
    'url'?: string;
    'outputs'?: Outputs;
    'destinations'?: Destinations;
    /**
    * An optional webhook callback URL used to receive status notifications when sources are uploaded and renditions processed.
    */
    'callback'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "outputs",
            "baseName": "outputs",
            "type": "Outputs"
        },
        {
            "name": "destinations",
            "baseName": "destinations",
            "type": "Destinations"
        },
        {
            "name": "callback",
            "baseName": "callback",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Source.attributeTypeMap;
    }
}

