/**
 * Shotstack
 * Official PHP SDK for the Shotstack Cloud Video Editing API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SourceResponseAttributes } from './sourceResponseAttributes';

/**
* The type of resource (a source), it\'s id and attributes of the source file.
*/
export class SourceResponseData {
    /**
    * The type of resource, in this case it is a source.
    */
    'type': string;
    /**
    * The source file id.
    */
    'id': string;
    'attributes': SourceResponseAttributes;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "SourceResponseAttributes"
        }    ];

    static getAttributeTypeMap() {
        return SourceResponseData.attributeTypeMap;
    }
}

