/**
 * Shotstack
 * Official Typescript SDK for the Shotstack Cloud Video Editing API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { StabilityAiGeneratedAssetOptions } from './stabilityAiGeneratedAssetOptions';

/**
* Generate assets using Stability AI. Stability AI provide a text-to-image service using Stable Diffusion. The Stability AI provider works on a bring-your-own-key basis, credentials are required and must be added via the  [dashboard](https://dashboard.shotstack.io/integrations/stability-ai), not in the request.
*/
export class StabilityAiGeneratedAsset {
    /**
    * The name of the provider - set to `stability-ai` for Stability AI.
    */
    'provider': StabilityAiGeneratedAsset.ProviderEnum = StabilityAiGeneratedAsset.ProviderEnum.STABILITY_AI;
    'options': StabilityAiGeneratedAssetOptions;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "provider",
            "baseName": "provider",
            "type": "StabilityAiGeneratedAsset.ProviderEnum"
        },
        {
            "name": "options",
            "baseName": "options",
            "type": "StabilityAiGeneratedAssetOptions"
        }    ];

    static getAttributeTypeMap() {
        return StabilityAiGeneratedAsset.attributeTypeMap;
    }
}

export namespace StabilityAiGeneratedAsset {
    export enum ProviderEnum {
        STABILITY_AI = <any> 'stability-ai'
    }
}
