/**
 * Shotstack
 * Official Typescript SDK for the Shotstack Cloud Video Editing API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { StabilityAiTextToImageOptions } from './stabilityAiTextToImageOptions';

/**
* Generate assets using Stability AI provider AI services.  The following AI generation services are available: <ul>   <li><a href=\"#tocs_stabilityaitexttoimageoptions\">StabilityAiTextToImageOptions</a></li> </ul>
*/
export class StabilityAiGeneratedAssetOptions {
    /**
    * The type of asset to generate - set to `text-to-image` for text-to-image.
    */
    'type': StabilityAiGeneratedAssetOptions.TypeEnum = StabilityAiGeneratedAssetOptions.TypeEnum.TEXT_TO_IMAGE;
    /**
    * The text prompt to generate an image from.
    */
    'prompt': string;
    /**
    * The engine (model) to use for generating the image. Select from the list of available engines: <ul>   <li>`stable-diffusion-xl-1024-v0-9`</li>   <li>`stable-diffusion-xl-1024-v1-0`</li>   <li>`stable-diffusion-v1-6`</li>   <li>`stable-diffusion-512-v2-1`</li>   <li>`stable-diffusion-xl-beta-v2-2-2`</li> </ul>
    */
    'engine'?: StabilityAiGeneratedAssetOptions.EngineEnum = StabilityAiGeneratedAssetOptions.EngineEnum.XL_1024_V1_0;
    /**
    * The width of the image in pixels. Must be divisible by 64.
    */
    'width': number;
    /**
    * The height of the image in pixels. Must be divisible by 64.
    */
    'height': number;
    /**
    * The number of iterative diffusion steps to run. A number between 10 and 50.
    */
    'steps'?: number = 30;
    /**
    * Using the same seed can help you create images that look similar. Set to 0 for a random seed. A number between 0 and 4294967295.
    */
    'seed'?: number = 0;
    /**
    * Determines how closely the generated image will match the prompt. Lower numbers allow for more creative freedom. A number between 0 and 35.
    */
    'cfgScale'?: number = 7;
    /**
    * Apply a preset to generate an image in a particular style. Select from the list of available presets: <ul>   <li>`3d-model`</li>   <li>`analog-film`</li>   <li>`anime`</li>   <li>`cinematic`</li>   <li>`comic-book`</li>   <li>`digital-art`</li>   <li>`enhance`</li>   <li>`fantasy-art`</li>   <li>`isometric`</li>   <li>`line-art`</li>   <li>`low-poly`</li>   <li>`modeling-compound`</li>   <li>`neon-punk`</li>   <li>`origami`</li>   <li>`photographic`</li>   <li>`pixel-art`</li>   <li>`tile-texture`</li> </ul>
    */
    'stylePreset'?: StabilityAiGeneratedAssetOptions.StylePresetEnum;

    static discriminator: string | undefined = "type";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "StabilityAiGeneratedAssetOptions.TypeEnum"
        },
        {
            "name": "prompt",
            "baseName": "prompt",
            "type": "string"
        },
        {
            "name": "engine",
            "baseName": "engine",
            "type": "StabilityAiGeneratedAssetOptions.EngineEnum"
        },
        {
            "name": "width",
            "baseName": "width",
            "type": "number"
        },
        {
            "name": "height",
            "baseName": "height",
            "type": "number"
        },
        {
            "name": "steps",
            "baseName": "steps",
            "type": "number"
        },
        {
            "name": "seed",
            "baseName": "seed",
            "type": "number"
        },
        {
            "name": "cfgScale",
            "baseName": "cfgScale",
            "type": "number"
        },
        {
            "name": "stylePreset",
            "baseName": "stylePreset",
            "type": "StabilityAiGeneratedAssetOptions.StylePresetEnum"
        }    ];

    static getAttributeTypeMap() {
        return StabilityAiGeneratedAssetOptions.attributeTypeMap;
    }
}

export namespace StabilityAiGeneratedAssetOptions {
    export enum TypeEnum {
        TEXT_TO_IMAGE = <any> 'text-to-image'
    }
    export enum EngineEnum {
        XL_1024_V0_9 = <any> 'stable-diffusion-xl-1024-v0-9',
        XL_1024_V1_0 = <any> 'stable-diffusion-xl-1024-v1-0',
        V1_6 = <any> 'stable-diffusion-v1-6',
        _512_V2_1 = <any> 'stable-diffusion-512-v2-1',
        XL_BETA_V2_2_2 = <any> 'stable-diffusion-xl-beta-v2-2-2'
    }
    export enum StylePresetEnum {
        _3D_MODEL = <any> '3d-model',
        ANALOG_FILM = <any> 'analog-film',
        ANIME = <any> 'anime',
        CINEMATIC = <any> 'cinematic',
        COMIC_BOOK = <any> 'comic-book',
        DIGITAL_ART = <any> 'digital-art',
        ENHANCE = <any> 'enhance',
        FANTASY_ART = <any> 'fantasy-art',
        ISOMETRIC = <any> 'isometric',
        LINE_ART = <any> 'line-art',
        LOW_POLY = <any> 'low-poly',
        MODELING_COMPOUND = <any> 'modeling-compound',
        NEON_PUNK = <any> 'neon-punk',
        ORIGAMI = <any> 'origami',
        PHOTOGRAPHIC = <any> 'photographic',
        PIXEL_ART = <any> 'pixel-art',
        TILE_TEXTURE = <any> 'tile-texture'
    }
}
