/**
 * Shotstack
 * Official PHP SDK for the Shotstack Cloud Video Editing API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MergeField } from './mergeField';

/**
* Configure the id and optional merge fields to render a template by id.
*/
export class TemplateRender {
    /**
    * The id of the template to render in UUID format.
    */
    'id': string;
    /**
    * An array of key/value pairs that provides an easy way to create templates with placeholders. The placeholders can be used to find and replace keys with values. For example you can search for the placeholder `{{NAME}}` and replace it with the value `Jane`. 
    */
    'merge'?: Array<MergeField>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "merge",
            "baseName": "merge",
            "type": "Array<MergeField>"
        }    ];

    static getAttributeTypeMap() {
        return TemplateRender.attributeTypeMap;
    }
}

