/**
 * Shotstack
 * Official PHP SDK for the Shotstack Cloud Video Editing API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Edit } from './edit';

/**
* A template is a saved [Edit](#tocs_edit) than can be loaded and re-used.
*/
export class Template {
    /**
    * The template name
    */
    'name': string;
    'template'?: Edit;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "template",
            "baseName": "template",
            "type": "Edit"
        }    ];

    static getAttributeTypeMap() {
        return Template.attributeTypeMap;
    }
}

