/**
 * Shotstack
 * Official Typescript SDK for the Shotstack Cloud Video Editing API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TemplateDataResponseData } from './templateDataResponseData';

/**
* The template data including the template name and [Edit](#tocs_edit).
*/
export class TemplateDataResponse {
    /**
    * `true` if successfully returned, else `false`.
    */
    'success': boolean;
    /**
    * `OK`, `Bad Request` or an error message.
    */
    'message': string;
    'response': TemplateDataResponseData;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "success",
            "baseName": "success",
            "type": "boolean"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "response",
            "baseName": "response",
            "type": "TemplateDataResponseData"
        }    ];

    static getAttributeTypeMap() {
        return TemplateDataResponse.attributeTypeMap;
    }
}

