/**
 * Shotstack
 * Official Typescript SDK for the Shotstack Cloud Video Editing API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TemplateResponseData } from './templateResponseData';

/**
* The response received after a [template](#create-template) is submitted. The template is saved and a unique template id is returned.
*/
export class TemplateResponse {
    /**
    * `true` if successfully created, else `false`.
    */
    'success': boolean;
    /**
    * `Created`, `Bad Request` or an error message.
    */
    'message': string;
    'response': TemplateResponseData;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "success",
            "baseName": "success",
            "type": "boolean"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "response",
            "baseName": "response",
            "type": "TemplateResponseData"
        }    ];

    static getAttributeTypeMap() {
        return TemplateResponse.attributeTypeMap;
    }
}

