/**
 * Shotstack
 * Official PHP SDK for the Shotstack Cloud Video Editing API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Edit } from './edit';

/**
* The response data returned with the [TemplateDataResponse](#tocs_templatedataresponse).
*/
export class TemplateDataResponseData {
    /**
    * The unique id of the template in UUID format.
    */
    'id': string;
    /**
    * The template name.
    */
    'name': string;
    /**
    * The owner id of the templates.
    */
    'owner': string;
    'template': Edit;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "owner",
            "baseName": "owner",
            "type": "string"
        },
        {
            "name": "template",
            "baseName": "template",
            "type": "Edit"
        }    ];

    static getAttributeTypeMap() {
        return TemplateDataResponseData.attributeTypeMap;
    }
}

