/**
 * Shotstack
 * Official Typescript SDK for the Shotstack Cloud Video Editing API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Clip } from './clip';

/**
* A track contains an array of clips. Tracks are layered on top of each other in the order in the array. The top most track will render on top of those below it.
*/
export class Track {
    /**
    * An array of Clips comprising of TitleClip, ImageClip or VideoClip.
    */
    'clips': Array<Clip>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "clips",
            "baseName": "clips",
            "type": "Array<Clip>"
        }    ];

    static getAttributeTypeMap() {
        return Track.attributeTypeMap;
    }
}

