/**
 * Shotstack
 * Official PHP SDK for the Shotstack Cloud Video Editing API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Destinations } from './destinations';

/**
* The asset URL to fetch and transfer to a destination.
*/
export class Transfer {
    /**
    * The file URL to fetch and transfer.
    */
    'url': string;
    /**
    * An identifier for the asset which must be provided by the client. The identifier does not need to be unique.
    */
    'id': string;
    /**
    * Specify the storage locations and hosting services to send the file to.
    */
    'destinations': Array<Destinations>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "destinations",
            "baseName": "destinations",
            "type": "Array<Destinations>"
        }    ];

    static getAttributeTypeMap() {
        return Transfer.attributeTypeMap;
    }
}

