/**
 * Shotstack
 * Official Typescript SDK for the Shotstack Cloud Video Editing API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Generate a transcription of the audio in the video. The transcription can be output as a file in SRT or VTT format.
*/
export class Transcription {
    /**
    * The output format of the transcription file. The following formats are available: <ul>   <li>`srt` - SRT captions format</li>   <li>`vtt` - VTT captions format</li> </ul>
    */
    'format'?: Transcription.FormatEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "format",
            "baseName": "format",
            "type": "Transcription.FormatEnum"
        }    ];

    static getAttributeTypeMap() {
        return Transcription.attributeTypeMap;
    }
}

export namespace Transcription {
    export enum FormatEnum {
        SRT = <any> 'srt',
        VTT = <any> 'vtt'
    }
}
