/**
 * Shotstack
 * Official PHP SDK for the Shotstack Cloud Video Editing API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TransferResponseAttributes } from './transferResponseAttributes';

/**
* The type of resource (an asset) and the transfer attributes. Returned with [TransferResponse](#tocs_transferresponse).
*/
export class TransferResponseData {
    /**
    * The type of resource, in this case it is an asset.
    */
    'type'?: string;
    'attributes'?: TransferResponseAttributes;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "TransferResponseAttributes"
        }    ];

    static getAttributeTypeMap() {
        return TransferResponseData.attributeTypeMap;
    }
}

