/**
 * Shotstack
 * Shotstack is a video, image and audio editing service that allows for the automated generation of videos, images and audio using JSON and a RESTful API.  You arrange and configure an edit and POST it to the API which will render your media and provide a file location when complete.  For more details visit [shotstack.io](https://shotstack.io) or checkout our [getting started](https://shotstack.io/docs/guide/) documentation.  There are three API\'s, one for editing and generating assets (Edit API), one for managing hosted assets (Serve API) and one for ingesting and transforming source assets (Ingest API).  Each API has it\'s own base URL and collection of endpoints. Each API uses the same set of API keys.  **[Edit API](#shotstack-edit)** - [https://api.shotstack.io/edit/{version}](#)<br> Edit videos, images and audio assets in the cloud using a simple JSON schema and templates.  **[Serve API](#shotstack-serve)** - [https://api.shotstack.io/serve/{version}](#)<br> Inspect and manage the hosting of assets generated by the Edit and Ingest APIs.  **[Ingest API](#shotstack-ingest)** - [https://api.shotstack.io/ingest/{version}](#)<br> Ingest (upload, store and transform) source footage, images, audio and fonts to be used by the Edit API.  **[Create API](#shotstack-create)** - [https://api.shotstack.io/create/{version}](#)<br> Generate images, videos, voice overs and text using built in and third party generative AI providers. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* In and out transitions for a clip - i.e. fade in and fade out
*/
export class Transition {
    /**
    * The transition in. Available transitions are:   <ul>     <li>`fade` - fade in</li>     <li>`reveal` - reveal from left to right</li>     <li>`wipeLeft` - fade across screen to the left</li>     <li>`wipeRight` - fade across screen to the right</li>     <li>`slideLeft` - move slightly left and fade in</li>     <li>`slideRight` - move slightly right and fade in</li>     <li>`slideUp` - move slightly up and fade in</li>     <li>`slideDown` - move slightly down and fade in</li>     <li>`carouselLeft` - slide in from right to left</li>     <li>`carouselRight` - slide in from left to right</li>     <li>`carouselUp` - slide in from bottom to top</li>     <li>`carouselDown` - slide in from top to bottom</li>     <li>`shuffleTopRight` - rotate in from top right</li>     <li>`shuffleRightTop` - rotate in from right top</li>     <li>`shuffleRightBottom` - rotate in from right bottom</li>     <li>`shuffleBottomRight` - rotate in from bottom right</li>     <li>`shuffleBottomLeft` - rotate in from bottom left</li>     <li>`shuffleLeftBottom` - rotate in from left bottom</li>     <li>`shuffleLeftTop` - rotate in from left top</li>     <li>`shuffleTopLeft` - rotate in from top left</li>     <li>`zoom` - fast zoom in</li>   </ul> The transition speed can also be controlled by appending `Fast` or `Slow` to the transition, e.g. `fadeFast` or `CarouselLeftSlow`.
    */
    '_in'?: Transition.InEnum;
    /**
    * The transition out. Available transitions are:   <ul>     <li>`fade` - fade out</li>     <li>`reveal` - reveal from right to left</li>     <li>`wipeLeft` - fade across screen to the left</li>     <li>`wipeRight` - fade across screen to the right</li>     <li>`slideLeft` - move slightly left and fade out</li>     <li>`slideRight` - move slightly right and fade out</li>     <li>`slideUp` - move slightly up and fade out</li>     <li>`slideDown` - move slightly down and fade out</li>     <li>`carouselLeft` - slide out from right to left</li>     <li>`carouselRight` - slide out from left to right</li>     <li>`carouselUp` - slide out from bottom to top</li>     <li>`carouselDown` - slide out from top  to bottom</li>     <li>`shuffleTopRight` - rotate out from top right</li>     <li>`shuffleRightTop` - rotate out from right top</li>     <li>`shuffleRightBottom` - rotate out from right bottom</li>     <li>`shuffleBottomRight` - rotate out from bottom right</li>     <li>`shuffleBottomLeft` - rotate out from bottom left</li>     <li>`shuffleLeftBottom` - rotate out from left bottom</li>     <li>`shuffleLeftTop` - rotate out from left top</li>     <li>`shuffleTopLeft` - rotate out from top left</li>     <li>`zoom` - fast zoom out</li>   </ul> The transition speed can also be controlled by appending `Fast` or `Slow` to the transition, e.g. `fadeFast` or `CarouselLeftSlow`.
    */
    'out'?: Transition.OutEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "_in",
            "baseName": "in",
            "type": "Transition.InEnum"
        },
        {
            "name": "out",
            "baseName": "out",
            "type": "Transition.OutEnum"
        }    ];

    static getAttributeTypeMap() {
        return Transition.attributeTypeMap;
    }
}

export namespace Transition {
    export enum InEnum {
        Fade = <any> 'fade',
        FadeSlow = <any> 'fadeSlow',
        FadeFast = <any> 'fadeFast',
        Reveal = <any> 'reveal',
        RevealSlow = <any> 'revealSlow',
        RevealFast = <any> 'revealFast',
        WipeLeft = <any> 'wipeLeft',
        WipeLeftSlow = <any> 'wipeLeftSlow',
        WipeLeftFast = <any> 'wipeLeftFast',
        WipeRight = <any> 'wipeRight',
        WipeRightSlow = <any> 'wipeRightSlow',
        WipeRightFast = <any> 'wipeRightFast',
        SlideLeft = <any> 'slideLeft',
        SlideLeftSlow = <any> 'slideLeftSlow',
        SlideLeftFast = <any> 'slideLeftFast',
        SlideRight = <any> 'slideRight',
        SlideRightSlow = <any> 'slideRightSlow',
        SlideRightFast = <any> 'slideRightFast',
        SlideUp = <any> 'slideUp',
        SlideUpSlow = <any> 'slideUpSlow',
        SlideUpFast = <any> 'slideUpFast',
        SlideDown = <any> 'slideDown',
        SlideDownSlow = <any> 'slideDownSlow',
        SlideDownFast = <any> 'slideDownFast',
        CarouselLeft = <any> 'carouselLeft',
        CarouselLeftSlow = <any> 'carouselLeftSlow',
        CarouselLeftFast = <any> 'carouselLeftFast',
        CarouselRight = <any> 'carouselRight',
        CarouselRightSlow = <any> 'carouselRightSlow',
        CarouselRightFast = <any> 'carouselRightFast',
        CarouselUp = <any> 'carouselUp',
        CarouselUpSlow = <any> 'carouselUpSlow',
        CarouselUpFast = <any> 'carouselUpFast',
        CarouselDown = <any> 'carouselDown',
        CarouselDownSlow = <any> 'carouselDownSlow',
        CarouselDownFast = <any> 'carouselDownFast',
        ShuffleTopRight = <any> 'shuffleTopRight',
        ShuffleTopRightSlow = <any> 'shuffleTopRightSlow',
        ShuffleTopRightFast = <any> 'shuffleTopRightFast',
        ShuffleRightTop = <any> 'shuffleRightTop',
        ShuffleRightTopSlow = <any> 'shuffleRightTopSlow',
        ShuffleRightTopFast = <any> 'shuffleRightTopFast',
        ShuffleRightBottom = <any> 'shuffleRightBottom',
        ShuffleRightBottomSlow = <any> 'shuffleRightBottomSlow',
        ShuffleRightBottomFast = <any> 'shuffleRightBottomFast',
        ShuffleBottomRight = <any> 'shuffleBottomRight',
        ShuffleBottomRightSlow = <any> 'shuffleBottomRightSlow',
        ShuffleBottomRightFast = <any> 'shuffleBottomRightFast',
        ShuffleBottomLeft = <any> 'shuffleBottomLeft',
        ShuffleBottomLeftSlow = <any> 'shuffleBottomLeftSlow',
        ShuffleBottomLeftFast = <any> 'shuffleBottomLeftFast',
        ShuffleLeftBottom = <any> 'shuffleLeftBottom',
        ShuffleLeftBottomSlow = <any> 'shuffleLeftBottomSlow',
        ShuffleLeftBottomFast = <any> 'shuffleLeftBottomFast',
        ShuffleLeftTop = <any> 'shuffleLeftTop',
        ShuffleLeftTopSlow = <any> 'shuffleLeftTopSlow',
        ShuffleLeftTopFast = <any> 'shuffleLeftTopFast',
        ShuffleTopLeft = <any> 'shuffleTopLeft',
        ShuffleTopLeftSlow = <any> 'shuffleTopLeftSlow',
        ShuffleTopLeftFast = <any> 'shuffleTopLeftFast',
        Zoom = <any> 'zoom'
    }
    export enum OutEnum {
        Fade = <any> 'fade',
        FadeSlow = <any> 'fadeSlow',
        FadeFast = <any> 'fadeFast',
        Reveal = <any> 'reveal',
        RevealSlow = <any> 'revealSlow',
        RevealFast = <any> 'revealFast',
        WipeLeft = <any> 'wipeLeft',
        WipeLeftSlow = <any> 'wipeLeftSlow',
        WipeLeftFast = <any> 'wipeLeftFast',
        WipeRight = <any> 'wipeRight',
        WipeRightSlow = <any> 'wipeRightSlow',
        WipeRightFast = <any> 'wipeRightFast',
        SlideLeft = <any> 'slideLeft',
        SlideLeftSlow = <any> 'slideLeftSlow',
        SlideLeftFast = <any> 'slideLeftFast',
        SlideRight = <any> 'slideRight',
        SlideRightSlow = <any> 'slideRightSlow',
        SlideRightFast = <any> 'slideRightFast',
        SlideUp = <any> 'slideUp',
        SlideUpSlow = <any> 'slideUpSlow',
        SlideUpFast = <any> 'slideUpFast',
        SlideDown = <any> 'slideDown',
        SlideDownSlow = <any> 'slideDownSlow',
        SlideDownFast = <any> 'slideDownFast',
        CarouselLeft = <any> 'carouselLeft',
        CarouselLeftSlow = <any> 'carouselLeftSlow',
        CarouselLeftFast = <any> 'carouselLeftFast',
        CarouselRight = <any> 'carouselRight',
        CarouselRightSlow = <any> 'carouselRightSlow',
        CarouselRightFast = <any> 'carouselRightFast',
        CarouselUp = <any> 'carouselUp',
        CarouselUpSlow = <any> 'carouselUpSlow',
        CarouselUpFast = <any> 'carouselUpFast',
        CarouselDown = <any> 'carouselDown',
        CarouselDownSlow = <any> 'carouselDownSlow',
        CarouselDownFast = <any> 'carouselDownFast',
        ShuffleTopRight = <any> 'shuffleTopRight',
        ShuffleTopRightSlow = <any> 'shuffleTopRightSlow',
        ShuffleTopRightFast = <any> 'shuffleTopRightFast',
        ShuffleRightTop = <any> 'shuffleRightTop',
        ShuffleRightTopSlow = <any> 'shuffleRightTopSlow',
        ShuffleRightTopFast = <any> 'shuffleRightTopFast',
        ShuffleRightBottom = <any> 'shuffleRightBottom',
        ShuffleRightBottomSlow = <any> 'shuffleRightBottomSlow',
        ShuffleRightBottomFast = <any> 'shuffleRightBottomFast',
        ShuffleBottomRight = <any> 'shuffleBottomRight',
        ShuffleBottomRightSlow = <any> 'shuffleBottomRightSlow',
        ShuffleBottomRightFast = <any> 'shuffleBottomRightFast',
        ShuffleBottomLeft = <any> 'shuffleBottomLeft',
        ShuffleBottomLeftSlow = <any> 'shuffleBottomLeftSlow',
        ShuffleBottomLeftFast = <any> 'shuffleBottomLeftFast',
        ShuffleLeftBottom = <any> 'shuffleLeftBottom',
        ShuffleLeftBottomSlow = <any> 'shuffleLeftBottomSlow',
        ShuffleLeftBottomFast = <any> 'shuffleLeftBottomFast',
        ShuffleLeftTop = <any> 'shuffleLeftTop',
        ShuffleLeftTopSlow = <any> 'shuffleLeftTopSlow',
        ShuffleLeftTopFast = <any> 'shuffleLeftTopFast',
        ShuffleTopLeft = <any> 'shuffleTopLeft',
        ShuffleTopLeftSlow = <any> 'shuffleTopLeftSlow',
        ShuffleTopLeftFast = <any> 'shuffleTopLeftFast',
        Zoom = <any> 'zoom'
    }
}
