/**
 * Shotstack
 * Official PHP SDK for the Shotstack Cloud Video Editing API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The id and attributes of the upload file including the signed URL to send the binary file data to.
*/
export class UploadResponseAttributes {
    /**
    * The source id.
    */
    'id': string;
    /**
    * The signed URL to use in a PUT request to send the binary file to.
    */
    'url': string;
    /**
    * The time the upload request will expire. The signed URL will expire after one hour. Upload must complete within one hour.
    */
    'expires': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "expires",
            "baseName": "expires",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return UploadResponseAttributes.attributeTypeMap;
    }
}

